name: PDFs generieren und Website deployen

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build:
    uses: deluxeGitHub/md-to-web-and-pdf/.github/workflows/reusable-build.yml@main
    with:
      source_dir: docs
    permissions:
      contents: write
