title: "BTFV Dokumente"
description: "Offizielle Dokumente des BTFV e.V."

plugins:
  - jekyll-toc
  - jekyll-relative-links

relative_links:
  enabled: true

custom_templates:
  - meinverein

exclude:
  - scripts/
  - temp/
  - framework/
  - .framework/
