title: "BTFV Dokumente"
description: "Offizielle Dokumente des BTFV e.V."

plugins:
  - jekyll-toc
  - jekyll-relative-links

defaults:
  - scope:
      path: ""
    values:
      layout: default
      template: btfv

relative_links:
  enabled: true

custom_templates:
  - meinverein

exclude:
  - scripts/
  - temp/
  - framework/
  - .framework/
